### PR TITLE
add hero tag parameter

### PR DESCRIPTION
**Pull request by 55nknown**

### CODE REVIEW

**Comment by zuvola** [comment]
Thanks for the PR.
When I set the heroTag on example and tried to transition to the screen, the following error occurred.

```
FlutterError (There are multiple heroes that share the same tag within a subtree.
Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
```

Maybe it is because you have the same heroTag set for both the close and open buttons.

**Comment by 55nknown** [comment]
Yeah it occurred to me too. Perhaps a suffix should be added at the end of the hero tags for each FAB?

**Comment by zuvola** [comment]
I don't really see the significance of its existence as a property.
Wouldn't it be sufficient to set constants such as "ExpandableFab_CloseButton" or "ExpandableFab_OpenButton" to heroTag?

**Comment by zuvola** [comment]
I have implemented this in a different way.
If you find this inconvenient, I am sorry, but could you please send me another PR?

**Pull request closed without merging**
